### ISSUE TITLE
Outline is disabled at alpha 0

### ISSUE THREAD

**Issue by AAAYaKo** [TLabAltoh/Unity-SDF-UI-Toolkit#1]
I want to make a rectangle with rounded corners without a fill.

**Comment by TLabAltoh** [comment]
Hi AAAYako. Thank you for your review. I have incorporated your suggestion. Regarding the unfilled rectangle, I added the [onion option](https://iquilezles.org/articles/distfunctions2d/#:~:text=Making%20shapes%20annular). It's a bit different from what you requested for, but it can create a UI with holes (The issue of the UI being transparent when the colour alpha of the image component is zero will be addressed later). This repository is undergoing a destractive update over the last few weeks. I am changing the namespace, the repository name (because of spelling mistakes), etc ... When you are updating the module in your project, please clone this repository as a new one. I will also support the add from Unity package manager later.
